services:
  - type: web
    name: MuzikPlayz
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn MuzikPlayz.wsgi:application --bind 0.0.0.0:$PORT"
    disk:
      name: db-storage
      mountPath: /var/lib/sqlite
      sizeGB: 1
